-- Drops all tables
DROP TABLE IF EXISTS term CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS takenCourses CASCADE;