-- Drops all tables
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS usertakencourses CASCADE;
DROP TABLE IF EXISTS userplannedcourses CASCADE;
DROP TABLE IF EXISTS userfriends CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS terms CASCADE;